// <auto-generated />
using DestinyVaultSorter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DestinyVaultSorter.Migrations
{
    [DbContext(typeof(WeaponContext))]
    [Migration("20230420015154_TestDBCreate")]
    partial class TestDBCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("DestinyVaultSorter.Weapon", b =>
                {
                    b.Property<int>("weaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("weaponElement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("weaponLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("weaponName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("weaponType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("weaponId");

                    b.ToTable("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
